### ISSUE TITLE
[BUG REPORT] Selecting a file format (Firefox)

### ISSUE THREAD

**Issue by romainGuiet** [aarpon/hrm#11]
**Describe the bug**
At "Step 1/4 - Select Images", when selecting a file format it is reset to "Please choose a file format...".
Observed on Firefox 77.0.1 
BUT works fine on Chrome.

**To Reproduce**
Star firefox, 
Connect to hrm
Launch jobs
Try to select a file format

**Expected behavior**
The file format selected is not reset to "Please choose a file format..."

**Environment**
***Server-side***
Huygens Remote Manager v3.6 

***Client-side***
Firefox 77.0.1 ,  Win10

**Additional context**
No issue observed when using Chrome.

**Comment by danielsevilla** [comment]
Hi Romain,

That's a known issue in version 3.6. The problem should be fixed in the current 3.7 version. Could you please try that out? For a demo of the latest 3.7 version please see hrm.svi.nl.

Cheers,
Daniel

**Comment by imagejan** [comment]
I can confirm that format selection on Firefox has so far worked well for me with HRM 3.7 (while I did see the issues with HRM 3.6 as well).

**Comment by aarpon** [comment]
Thanks for the feedback!

**Comment by lacan** [comment]
Thank you all for the feedback. We have updated HRM and this issue seems fixed. All the best
