### ISSUE TITLE
[BUG REPORT] Login to AD fails in HRM 3.9.0

### ISSUE THREAD

**Issue by grzybeks** [aarpon/hrm#23]
**Describe the bug**
AD login with previously working HRM configuration from version 3.8.0 fails, producing a HTTP 500 error.

**To Reproduce**
HRM with ActiveDirectory configuration and $REAL_PRIMARY_GROUP = true setting.

**Expected behavior**
Login to HRM working with ActiveDirectory logins and having group information useable for login and other kinds of filtering.

**Screenshots**
N/A

**Environment**
***Server-side***
Ubuntu 22.04.3, PHP 8.1, MySQL 5.7.43 (on remote server), Apache 2.4.52.

***Client-side***
Google Chrome 119.0.6045.124, Windows 10.

**Additional context**
Trying to login on the Web UI in HRM 3.9.0 fails with a previously working ActiveDirectory configuration.
Error from the log-file:
```
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /usr/local/hrm_3.9.0/inc/user/proxy/ActiveDirectoryProxy.php:374\nStack trace:\n#0 /usr/local/hrm_3.9.0/inc/user/UserV2.php(614): hrm\\user\\proxy\\ActiveDirectoryProxy->getGroup()\n#1 /usr/local/hrm_3.9.0/inc/user/UserV2.php(403): hrm\\user\\UserV2->load()\n#2 /usr/local/hrm_3.9.0/login.php(86): hrm\\user\\UserV2->logIn()\n#3 {main}\n  thrown in /usr/local/hrm_3.9.0/inc/user/proxy/ActiveDirectoryProxy.php on line 374, referer: http://hrm.fmi.ch/
```
I could successfully login only after changing `$REAL_PRIMARY_GROUP = true;`
to `$REAL_PRIMARY_GROUP = false;` in active_directory_config.inc. However, any login filtering by group membership and other kinds of filtering (e.g. template visibility filtering) that require group information does not work.

With turning on debugging logs, it looks like AD login works fine. Only the retrieval of group memberships does not work, resulting in the exception listed above.

**Comment by KevinNamink** [comment]
We had to update the AD library a lot of versions to get it compatible with PHP 8.1+. We couldn't test all types of setups since we didn't have all setups available. I have no doubt it can work, but maybe not all settings are forwards compatible.

If I understand correctly you need to and are using the $AD_USERNAME_SUFFIX etc. settings in the config file?
If so, I faintly recall that some settings might need to be slightly different than before. I'm not sure I have the virtual machines where I tested this on anymore.

I also know there can be bugs with the return value of many AD related functions that have changed from always returning something that is "true" or "false" to sometimes "null" (which cannot be used in if statements the same way). If you notice an error mentioning something like that it could have slipped past me.

I'm not sure if there is anything confidential about the AD settings, but it could be helpful to see them if I recover my VM or set up a new one. If preferred you can reach me more directly via support emails to SVI.

**Comment by KevinNamink** [comment]
Some information:
The use of REAL_PRIMARY_GROUP in the package used here changed completely. That it might not work as before is not that surprising to me. It used to be a parameter passed to the connection, now it is a function to be called on a user.
More or less the same is true for RECURSIVE_GROUPS. I had recreated the old behavior with the active directory setups I had at hand. 

> When working with REAL_PRIMARY_GROUP=true, I get the message ‘No primary group for user’ using your code.

This code simply caught the problem. I could foresee a situation where a second "attempt" would work if the first was caught properly, I guess this was not the case.

> Looking further into the code and with REAL_PRIMARY_GROUP=false, I think I found a ‘bug’ / logic change compared to HRM 3.8.0 in line 382: (...)

Looking through this code more, there might be a change in logic. If you use "Example 2" from [active_directory_config.inc.sample](https://github.com/aarpon/hrm/blob/7d74dede7b259fc9a61c29b538d4eac7007131f8/config/samples/active_directory_config.inc.sample#L123C17-L123C17)  the behavior might have changed. 
I wasn't able to test this behavior as I have no complicated active_directory setup available. I think your suggestion should be part of a secondary check: as I understand it now the `m_AuthorizedGroups` are the groups to check if a user can log in and the `m_ValidGroups` are the groups to show in the HRM.

> For my bug report, I thought that the filtering of visible templates was connected to missing group membership information, but I am now not sure anymore, unless there are more uses outside of the login process of getGroup(). Could this be another change introduced with HRM 3.9.0?

I was not aware of this feature, but it was not actively changed. Properly fixing this login might restore that behavior.

So I think a secondary loop is necessary in this "getGroup" function:
```php
    /**
     * Returns the group the user with given username belongs to.
     * @param string $username Username for which to query the group.
     * @param bool $verbose Set the verbosity of this function (to reproduce old log behavior).
     * @return string Group or "" if not found.
    */
    public function getGroup($username, $verbose = true)
    {
        // Attempt to get the user data with the username.
        $user = $this->getUser($username);
        if (!$user) {
            return "";
        }
        
        if ($this->m_RealPrimaryGroup) {
            $group = $user->getPrimaryGroup()->getName();
            if (in_array($group, $this->m_AuthorizedGroups)) {
                if ($verbose) {
                    Log::info('Group for username "' . $username . '": ' . $group);
                }
                return $group;
            }
        } else {
            foreach ($this->m_AuthorizedGroups as $group) {
                if ($user->inGroup($group, $recursive=$this->m_RecursiveGroups)) {
                    foreach ($this->m_ValidGroups as $validGroup) {
                        if ($user->inGroup($validGroup, $recursive=$this->m_RecursiveGroups)) {
                            $group = $validGroup;
                            if ($verbose) {
                                Log::info('Using ValidGroup for "' . $username . '": ' . $group);
                            }
                            break;
                        }
                    }
                    if ($verbose) {
                        Log::info('Group for username "' . $username . '": ' . $group);
                    }
                    return $group;
                }
            }
        }
        if ($verbose) {
            Log::info("Group for username $username not found in the list of authorized groups!");
        }
        return "";
    }
``` 
I think this is more in line with the old behavior for the "Example 2" situation for the active_directory_config.inc. NOTE: I haven't been able to test this new bit of code yet.

**Comment by KevinNamink** [comment]
Have you had time to work on this and did you manage to fix it?

If it is not fixed I could try setting up an active directory with a similar configuration to more directly help.
If it is fixed I'd like to update the repository.

**Comment by grzybeks** [comment]
Sorry, I did not have time to test your proposal yet.

FYI: in our active_directory_config.inc we have:
```
$VALID_GROUPS = array( <long list of strings > );
$AUTHORIZED_GROUPS = array();
```
I did not check what "Example 2" looks like.

**Comment by grzybeks** [comment]
Thank you for the follow-up and explaining the effect of our groups settings.
I reached out to the person who reported the additional, visible templates. It may take a while to get more information.

**Comment by grzybeks** [comment]
Hello Kevin,
I did not get further information from the person who mentioned the additional template.

**Comment by grzybeks** [comment]
Hello Kevin,
I did not get further information from the person who mentioned the additional templates.
Therefore, I close the issue now.
Thank you for your support!
