### ISSUE TITLE
[BUG REPORT] Outdated javascript libraries 

### ISSUE THREAD

**Issue by chdietrich** [aarpon/hrm#6]
**Describe the bug**
HRM 3.6.0 ships with outdated javascript libraries that are XSS vulnerable:
```
jqtree 1.1.0...: https://github.com/mbraak/jqTree/issues/437
jQuery 1.8.3...: https://www.cvedetails.com/vulnerability-list/vendor_id-6538/Jquery.html
jquery-ui 1.9.1: https://github.com/jquery/api.jqueryui.com/issues/281
```

**Environment**
***Server-side***
HRM 3.6.0

**Additional context**
I have not checked whether this has an effect on HRM itself, if necessary I can take a closer look.

**Comment by aarpon** [comment]
Being worked on in branch [bug/6](https://github.com/aarpon/hrm/tree/bugs/6). 

Commit [68cac8fa](https://github.com/aarpon/hrm/commit/68cac8faa13d7f969d276ae5317db859f21be40d):  Upgrade **jQuery** to version **3.3.x** (managed by composer), **jQuery-UI** to version **1.12.x** (managed by composer) and **jqTree** to version **1.4.10** (direct download).

If you have a chance, please test (functionality and styling).

**Comment by christianddietrich** [comment]
> If you have a chance, please test

I've noticed the following:

"Launch jobs" -> "Images available on server" stays empty after selecting "Image file format".

In the master branch the images are listed correctly. Thanks!
